### ISSUE TITLE
Return job-constraint-supported and job-resolvers-supported attributes 

### ISSUE THREAD

**Issue by HPRoss** [HPInc/jipp#112]
I have an interest in having the attributes returned for two ipp responses if they are available from a printer.

job-resolvers-supported and job-constraints-supported per PWG 5100.7-2019 https://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext20-20190816-5100.7.pdf

**Acceptance Criteria**

- If the printer support these attributes return these attributes
- If printer does not have these attributes don't return default values - in this scenario don't return these attributes at all

**Comment by GladeDiviney** [comment]
For a workaround, see https://github.com/HPInc/jipp/tree/issue112 particularly the following files:

https://github.com/HPInc/jipp/pull/113/files#diff-6f45b99888fc56f93006a04b0afdbdd546947369508b18e45d0d6b24d54347b3

https://github.com/HPInc/jipp/blob/d093b21816b3ff7fbc61392c09893820160d539c/jipp-core/src/test/java/com/hp/jipp/encoding/CollectionTest.java#L59

https://github.com/HPInc/jipp/pull/113/files#diff-ce6eaef35db064e8491aadeb87f4d0a88f0bdfce3269cafe5b164923e6b9c292

Notes:

* It was a little harder than expected because `AttributeCollection.Converter` uses a Kotlin feature (default interface methods) that is hard to bridge over to Java. My fix above is to include a single Kotlin file to make them accessible to Java.
* The example shows just `JobResolversSupported` but `JobConstraintsSupported` would be similar.
* media-col according to the attribute appears as an entire media-col collection so the collection elements are NOT exposed at the top. That is, you will find `job-resolvers-supported.media-col.media-top-margin` NOT `job-resolvers-supported.media-top-margin`.
* The code I wrote is against the current version (0.7.x) and may need modifications to run in earlier releases.

Overall: this is a hack, and needs to be better supported in the type itself. So this issue should remain open until a real fix is in place.
