### ISSUE TITLE
How to add 'sides' job attribute?

### ISSUE THREAD

**Issue by Rbcum** [HPInc/jipp#58]
Hi, I run the following code and the printer response with client-error-bad-request(1024) r=0x7b, is it some syntax error or just the printer does not support this attribute?
```
        val printRequest = IppPacket(
            Operation.printJob, 123,
            groupOf(
                operationAttributes,
                attributesCharset.of("utf-8"),
                attributesNaturalLanguage.of("en"),
                printerUri.of(uri),
                requestingUserName.of("jprint"),
                documentFormat.of("application/pdf")
            ),
            groupOf(
                jobAttributes,
                sides.of("two-sided-long-edge")
            )
        )
        val transport = HttpIppClientTransport()
        val request = IppPacketData(printRequest, FileInputStream(inputFile))
        val (packet) = transport.sendData(uri, request)
```

**Comment by Rbcum** [comment]
I got it, the printer configuration is not right, close.

**Comment by GladeDiviney** [comment]
Thanks for updating the issue!

By the way, I would recommend using `sides.of(Sides.twoSidedLongEdge)` so you don't have to worry about mistyping the value. All of the [published IPP keywords](https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xhtml) are supported in this way.

**Comment by sebastian-schmitt** [comment]
could you elaborate on what was not right with your request? I'm struggling with a similar issue and I am therefore interested in your solution. Thanks in advance!

**Comment by Rbcum** [comment]
@sebastian-schmitt My HP printer has a configuration web page, and after change the one/two side setting, it worked.

**Comment by sebastian-schmitt** [comment]
> @sebastian-schmitt My HP printer has a configuration web page, and after change the one/two side setting, it worked.

Thank you for taking your time to come back here and help me out.
In the meantime I could find the cause of my problem: 

The HP-Printers treat the `requesting-user-name` attribute of a `Get-Job-Attributes` request as a 'MUST be provided by the client' attribute instead of 'SHOULD be provided'. And furthermore,  IPP requires you to provide the attributes in  exactly this order. 

So I corrected my attribute-ordering, provided the printer with a made-up username and everything worked out well.

**Comment by GladeDiviney** [comment]
I'm curious if there was some way the API could have helped flag this. At present it's designed to give full control to the user to decide which attributes appear and in what order. Users wouldn't expect to have to change the order or add attributes.

**Comment by sebastian-schmitt** [comment]
I guess each IPP operation would have to define a complete ordering on the set of possible attributes - so that all attributes that have been set by the API user can be sorted accordingly just before writing the final message to the wire. This order could even be extended to tell the different roles of the attributes (to check at the end, whether all "MUST be present" attributes have been set).

Providing the users with this kind of runtime-check seems a nice (because time and stress saving) extra feature.

But: I'm already very happy with all the abstractions you provide me with so far! So a thousand thanks for all the work you put in and shared with us!

**Comment by GladeDiviney** [comment]
You're welcome, and I'm glad to help!

Most attributes don't have a specified order. What if each attribute type had an optional priority field? This would be honored only when using a dsl to create attribute groups. Unprioritized attributes would keep their original order.

**Comment by wifiprintguy** [comment]
@sebastian-schmitt can you describe an example of the ordering issue you are seeing with HP printers in more detail? Other than the attributes at the start of the operation group (attributes-charset, attributes-natural-language, printer-uri / job-uri / job-id / system-uri, depending on the operation in question) there should be no required ordering for other attributes in the operation group or within any other group. If Printers are imposing ordering requirements for other attributes, that is unfortunate.

**Comment by sebastian-schmitt** [comment]
> @sebastian-schmitt can you describe an example of the ordering issue you are seeing with HP printers in more detail? Other than the attributes at the start of the operation group (attributes-charset, attributes-natural-language, printer-uri / job-uri / job-id / system-uri, depending on the operation in question) there should be no required ordering for other attributes in the operation group or within any other group. If Printers are imposing ordering requirements for other attributes, that is unfortunate.

I was only affected by this single example described above ([https://tools.ietf.org/html/rfc2911#section-3.3.4.1](https://tools.ietf.org/html/rfc2911#section-3.3.4.1)) - but I guess the `requesting-user-name` is part of exactly this starting part you are talking about. But also for those first attributes, there is no ordering imposed by the API (that's why I was landing here in the first place).

**Comment by wifiprintguy** [comment]
@sebastian-schmitt I'm sorry but your example wasn't clear, at least not to me. Where was "requesting-user-name" in the operation group, and what does the MUST vs. the SHOULD have to do with the ordering?

@gladed Given that IPP/1.1 and IPP/2.0 requires that "attributes-charset" and "attributes-natural-language" need to be the first and second attributes in the operations group (https://tools.ietf.org/html/rfc8011#section-4.1.4), does jipp enforce that ordering?

**Comment by GladeDiviney** [comment]
@wifiprintguy JIPP does not, and I'd like to fix this, but Java calling conventions make this tricky. This is not the first time this has come up, so I'm opening a ticket for it, #77.

@sebastian-schmitt The request-name thing is unfortunate but I have seen that limitation too in some printers. I think it's also smart to include it as the very next attribute after other required ones just in case. Since this isn't part of the spec it's probably just something to document and include in examples as a "good practice".

**Comment by sebastian-schmitt** [comment]
@wifiprintguy I made two mistakes when talking to the HP-Printer. One of them was to omit the `requesting-user-name` (so the MUST vs. SHOULD thing) - the other one followed my correction of the first one and affected the ordering of attributes:

I had:
`attributes-charset` > `attributes-natural-language` > `requesting-user-name` > `job-uri`

But it MUST be:
`attributes-charset` > `attributes-natural-language` >`job-uri` > `requesting-user-name`

@GladeDiviney This would definitely solve the problem - If @wifiprintguy is right and IPP requires a strict ordering of the here mentioned small subset of attributes only, it may result in a simpler solution if you would manage the ordering-information independent from the individual attributes.
